server:
  host: localhost
  port: 8080
  readTimeout: 5
  writeTimeout: 10
  gracefulTimeout: 5
  circuitbreaker:
    enabled: true
    timeout: 5
    interval: 0
registry:
  heartbeatInterval: 15
  services:
    - name: backend
      addr: "localhost:3000"
      whitelist:
        - "ALL"
      fallbackUri: "localhost:3001"
      health:
        enabled: true
        uri: "/health"
      auth:
        enabled: true
        secret: "/secrets/backend.txt"
        routes:
          - "/private"
ratelimiter:
  enabled: true
  maxRequestsPerMinute: 500
