server:
  host: localhost
  port: 8080
  readTimeout: 5
  writeTimeout: 10
registry:
  heartbeatInterval: 15
  services:
    - name: backend
      addr: "localhost:3000"
      whitelist:
        - "ALL"
      fallbackUri: "localhost:3001"
ratelimiter:
  maxRequestsPerMinute: 100
