server:
  host: localhost
  port: 8080
  readTimeout: 10
  writeTimeout: 10
registry:
  heartbeatInterval: 10
  services:
    - name: backend
      addr: "localhost:3000"
ratelimiter:
  maxRequestsPerMinute: 100