server:
  host: localhost
  port: 8080
  readTimeout: 5
  writeTimeout: 10
  gracefulTimeout: 5
  tlsconfig:
    enabled: false
    certFile: "path/to/cert.pem"
    keyFile: "path/to/key.pem"
  metrics:
    prefix: "gateway"
    buckets: [0.005, 0.01, 0.025, 0.05, 0.1]
registry:
  heartbeatInterval: 15
  services:
    - name: example
      addr: "localhost:3000"
      whitelist:
        - "ALL"
      fallbackUri: "localhost:3001"
      health:
        enabled: true
        uri: "/health"
      auth:
        enabled: true
        anonymous: false
        secret: "path/to/secret"
        routes:
          - "/private"
      cache:
        enabled: true
        expirationInterval: 5
        cleanupInterval: 10
      circuitbreaker:
        enabled: true
        timeout: 5
        interval: 0
        failureRatio: 0.5
ratelimiter:
  enabled: true
  maxRequests: 500
  cleanupInterval: 1
  eventInterval: 60
